config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("securitycontrol/", include("securityControl.urls", namespace="sc")),
    path("", include("fotoblog.urls", namespace="fotoblog")),
]

fotoblog/urls.py
from django.urls import path
from fotoblog.views import page_views, post_detail_views


app_name = "fotoblog"

urlpatterns = [
    path("", page_views, name="home_views"),
    path("<slug:page_slug>/", page_views, name="page_views"),
    path("<slug:page_slug>/<slug:post_slug>", page_views, name="page_views"),
    path("<slug:page_slug>/<slug:post_slug>/<int:post_id>",
         post_detail_views,
         name="post_details"),
]

securityControl/urls.py
from django.urls import path
from securityControl.views import page_views

app_name = "sc"

urlpatterns = [
    path("", page_views, name="sec-home-views"),
    path("<slug:page_slug>/", page_views, name="sec-home-views"),
    path("<slug:page_slug>/<slug:location>", page_views, name="sec-home-views"),
]

securityControl/models.py
from django.db import models
from django.core.validators import RegexValidator
from django.utils.text import slugify

tc_validator = RegexValidator(
    regex=r'^[1-9][0-9]{10}$',
    message="TC Kimlik Numarası 11 haneli olmalı ve 0 ile başlamamalıdır.")


class BaseModel(models.Model):
  first_name = models.CharField(max_length=100, null=False, blank=False)
  last_name = models.CharField(max_length=100, null=False, blank=False)
  tc_kimlik_no = models.CharField(max_length=11,
                                  null=False,
                                  blank=False,
                                  unique=True,
                                  validators=[tc_validator])

  class Meta:
    abstract = True


class Page(models.Model):
  title = models.CharField(max_length=100,
                           unique=True,
                           blank=False,
                           null=False)
  slug = models.SlugField(max_length=120, unique=True, null=False, blank=True)
  img = models.FileField(upload_to="page_img/")
  is_active = models.BooleanField(default=True)

  def save(self, *args, **kwargs):
    if not self.slug:
      self.slug = slugify(self.title)
    super().save(*args, **kwargs)

  def __str__(self):
    return self.title


class Ziyaretci(BaseModel):

  def __str__(self):
    return f'{self.first_name} {self.last_name}'


class Taseron(models.Model):
  ziyaretci = models.ForeignKey(Ziyaretci,
                                on_delete=models.CASCADE,
                                blank=False,
                                null=False)
  firma_adi = models.CharField(max_length=100)
  davet_eden = models.CharField(max_length=100)
  yapilacak_is = models.CharField(max_length=100)
  calisma_alani = models.CharField(max_length=100)
  is_inside = models.BooleanField(default=True)
  created_at = models.DateTimeField(auto_now_add=True)
  updated_at = models.DateTimeField(auto_now=True)

  def __str__(self):
    return self.firma_adi


class yuk_arac(models.Model):
  sofor = models.ForeignKey(Ziyaretci,
                            on_delete=models.CASCADE,
                            null=False,
                            blank=False)
  cekici_plaka = models.CharField(max_length=100,
                                  null=False,
                                  blank=False,
                                  unique=True)
  dorse_plaka = models.CharField(max_length=100,
                                 null=False,
                                 blank=False,
                                 unique=True)
  firma_adi = models.CharField(max_length=100, null=False, blank=False)
  arac_turu = models.CharField(max_length=100, null=False, blank=False)
  sevkiyat_bolumu = models.CharField(max_length=100, null=False, blank=False)
  gidecegi_yer = models.CharField(max_length=100, null=False, blank=False)
  aciklama = models.TextField(blank=True, null=True)
  is_inside = models.BooleanField(default=True)
  created_at = models.DateTimeField(auto_now_add=True)
  updated_at = models.DateTimeField(auto_now=True)


tel_validator = RegexValidator(
    regex=r'^[1-9][0-9]{9}$',
    message="Lütfen telefon numaranızı başında 0 olmadan girin!")


class Calısan(BaseModel):
  departman = models.CharField(max_length=100, blank=False, null=False)
  tel = models.CharField(max_length=10,
                         blank=False,
                         null=False,
                         validators=[tel_validator])
  is_active = models.BooleanField(default=True)

  def __str__(self):
    return f'{self.first_name} {self.last_name}'


km_validator = RegexValidator(
    regex=r'^[1-6]\d{0,5}$',
    message="Km bilgisi 0'dan farklı ve max. 6 haneli olabilir!")


class havuz_arac(models.Model):
  calisan = models.ForeignKey(Calısan,
                              null=False,
                              blank=False,
                              on_delete=models.CASCADE)
  plaka = models.CharField(max_length=100, null=False, blank=False)
  baslangic_km = models.CharField(max_length=6,
                                  null=True,
                                  blank=True,
                                  validators=[km_validator])
  son_km = models.CharField(max_length=6,
                            null=True,
                            blank=True,
                            validators=[km_validator])
  net_km = models.PositiveIntegerField(null=True, blank=True, editable=False)
  gidecegi_yer = models.CharField(max_length=100, null=False, blank=False)
  aciklama = models.TextField(blank=True, null=True)
  is_inside = models.BooleanField(default=True)
  giris_tarihi_saati = models.DateTimeField(null=True, blank=True)
  cikis_tarihi_saati = models.DateTimeField(null=True, blank=True)

  def save(self, *args, **kwargs):
    if self.baslangic_km and self.son_km:
      try:
        self.net_km = int(self.son_km) - int(self.baslangic_km)
      except ValueError:
        self.net_km = None
    else:
      self.net_km = None
    super().save(*args, **kwargs)

  def __str__(self):
    return self.plaka

securityControl/forms/forms.py
from django import forms
from django.db.models import fields
from django.forms import widgets
from securityControl.models import Ziyaretci, Taseron, yuk_arac, havuz_arac, Calısan


class ZiyaretciForm(forms.ModelForm):

    class Meta:
        model = Ziyaretci
        fields = "__all__"


class TaseronForm(forms.ModelForm):

    class Meta:
        model = Taseron
        fields = "__all__"

        exclude = ["is_inside", "is_outside"]


class yukAracForm(forms.ModelForm):

    class Meta:
        model = yuk_arac
        fields = "__all__"

        exclude = ["is_inside", "is_outside"]


class HavuzAracForm(forms.ModelForm):

    class Meta:
        model = havuz_arac
        fields = "__all__"

        exclude = [
            "is_inside",
        ]

        widgets = {
            "giris_tarihi_saati":
            forms.DateTimeInput(attrs={
                "type": "datetime-local",
                "class": "form-control"
            }, ),
            "cikis_tarihi_saati":
            forms.DateTimeInput(attrs={
                "type": "datetime-local",
                "class": "form-control"
            })
        }


class CalisanForm(forms.ModelForm):

    class Meta:
        model = Calısan
        fields = '__all__'

        exclude = [
            "is_active",
        ]

securityControl/views.py
from django.shortcuts import get_object_or_404, render, redirect
from securityControl.models import Page, Taseron, Ziyaretci, havuz_arac, yuk_arac
from securityControl.forms.forms import HavuzAracForm, TaseronForm, ZiyaretciForm, yukAracForm, CalisanForm
from django.contrib.auth.decorators import login_required
# Create your views here.

@login_required (login_url='/login/')
def page_views(request, page_slug=None, location=None):
    page = None
    sc_pages = None
    title = None
    if page_slug == None:
        title = "Ana Sayfa"
        sc_pages = Page.objects.filter(is_active=True)
        if sc_pages:
            sc_pages = sc_pages
        else:
            sc_pages = None
    if page_slug:
        if page_slug == "ziyaretci":
            return ziyaretci_views(request, page_slug, location)
        if page_slug == "taseron":
            return taseron_views(request, page_slug, location)
        if page_slug == "yuk-arac":
            return yuk_arac_views(request, page_slug, location)
        if page_slug == "havuz-arac":
            return havuz_arac_views(request, page_slug)
        else:
            page = get_object_or_404(Page, slug=page_slug, is_active=True)
            title = page.title

    context = dict(
        page_slug=page_slug,
        sc_pages=sc_pages,
        page_title=title,
        page=page,
    )
    return render(request, "sc_pages/sec-home-views.html", context)


def ziyaretci_views(request, page_slug, location=None):
    ziyaretciler = Ziyaretci.objects.all()
    if ziyaretciler:
        ziyaretciler = ziyaretciler
        page_slug = page_slug
    else:
        ziyaretciler = None
        page_slug = page_slug
    if request.method == "POST":
        ziyaretci_form = ZiyaretciForm(request.POST)
        if ziyaretci_form.is_valid():
            ziyaretci_form.save()
            if location:
                return redirect("sc:sec-home-views", page_slug=location)
            else:
                return redirect("sc:sec-home-views", page_slug=page_slug)

    else:
        ziyaretci_form = ZiyaretciForm()
    sc_pages = None
    title = "Ziyaretçi Kayıt"
    context = dict(
        page_title=title,
        sc_pages=sc_pages,
        ziyaretci_form=ziyaretci_form,
        ziyaretciler=ziyaretciler,
        page_slug=page_slug,
    )
    return render(request, "sc_pages/sec-home-views.html", context)


def taseron_views(request, page_slug, location=None):
    ziyaretci_form = ZiyaretciForm()
    ziyaretciler = Ziyaretci.objects.all()
    taseronlar = Taseron.objects.all()
    if taseronlar:
        taseronlar = taseronlar
        page_slug = page_slug
    else:
        taseronlar = None
        page_slug = page_slug
    if request.method == "POST":
        taseron_form = TaseronForm(request.POST)
        if taseron_form.is_valid():
            taseron_form.save()
            if location:
                return redirect("sc:sec-home-views", page_slug=location)
            else:
                return redirect("sc:sec-home-views", page_slug=page_slug)

    else:
        taseron_form = TaseronForm()
    context = dict(
        taseron_form=taseron_form,
        page_slug=page_slug,
        taseronlar=taseronlar,
        ziyaretci_form=ziyaretci_form,
        ziyaretciler=ziyaretciler,
    )
    return render(request, "sc_pages/sec-home-views.html", context)


def yuk_arac_views(request, page_slug, location=None):
    ziyaretci_form = ZiyaretciForm()
    ziyaretciler = Ziyaretci.objects.all()
    ziyaretciler = Ziyaretci.objects.all()
    yuk_araclari = yuk_arac.objects.filter(is_inside=True)
    if yuk_araclari:
        yuk_araclari = yuk_araclari
    else:
        yuk_araclari = None

    if request.method == "POST":
        yuk_arac_form = yukAracForm(request.POST)
        if yuk_arac_form.is_valid():
            yuk_arac_form.save()
            if location:
                return redirect("sc:sec-home-views", page_slug=location)
            else:
                return redirect("sc:sec-home-views", page_slug=page_slug)

        else:
            yuk_arac_form = yukAracForm()

    else:
        yuk_arac_form = yukAracForm()

    context = dict(
        yuk_arac_form=yuk_arac_form,
        yuk_araclari=yuk_araclari,
        page_slug=page_slug,
        ziyaretci_form=ziyaretci_form,
        ziyaretciler=ziyaretciler,
    )
    return render(request, "sc_pages/sec-home-views.html", context)


def havuz_arac_views(request, page_slug):
    havuz_araclari = havuz_arac.objects.all()
    if havuz_araclari:
        havuz_araclari = havuz_araclari
    else:
        havuz_araclari = None
    if request.method == "POST":
        calisan_form = CalisanForm(request.POST)
        if calisan_form.is_valid():
            calisan_form.save()
            return redirect("sc:sec-home-views", page_slug=page_slug)
        havuz_arac_form = HavuzAracForm(request.POST)
        if havuz_arac_form.is_valid():
            havuz_arac_form.save()
            return redirect("sc:sec-home-views", page_slug=page_slug)
    else:
        havuz_arac_form = HavuzAracForm()
        calisan_form = CalisanForm()
    context = dict(
        havuz_arac_form=havuz_arac_form,
        page_slug=page_slug,
        havuz_araclari=havuz_araclari,
        calisan_form=calisan_form,
    )
    return render(request, "sc_pages/sec-home-views.html", context)

securityControl/templates/components/footer.html
<div class="card text-center m-0">
  <div class="card-header">
    <ul class="nav nav-pills card-header-pills">
      <li class="nav-item">
        <a class="nav-link active" href="#">Active</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" aria-disabled="true">Disabled</a>
      </li>
    </ul>
  </div>
  <div class="card-body">
    <h5 class="card-title">Special title treatment</h5>
    <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
    <a href="#" class="btn btn-primary">Go somewhere</a>
  </div>
</div>

securityControl/templates/components/havuz-arac-layout.html
<div class="row d-flex justify-content-around">
  <div class="col-12 col-md-4 d-flex flex-column align-items-center">
  <h3 class="text-center text-success mb-3">Havuz Araç Kayıt</h3>
    <div class="w-100">

      <button class="btn btn-outline-info mb-1" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasScrolling" aria-controls="offcanvasScrolling">+Çalışan Ekle</button>

      <div class="offcanvas offcanvas-start" data-bs-scroll="true" data-bs-backdrop="false" tabindex="-1" id="offcanvasScrolling" aria-labelledby="offcanvasScrollingLabel">
        <div class="offcanvas-header">
          <h5 class="offcanvas-title" id="offcanvasScrollingLabel">Çalışan Kayıt Formu</h5>
          <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
        </div>
        <div class="offcanvas-body">

          <form action="{% url 'sc:sec-home-views' page_slug=location %}" method="post" class="row flex-column mb-3 g-3">
          {% load crispy_forms_tags %}
            {% csrf_token %}
            {{ calisan_form|crispy }}
            <button class="btn btn-outline-success w-25 mx-auto" type="submit">Kaydet</button>
          </form>
        </div>
      </div>

        <form action="" method="post" class="row flex-column mb-3 g-3">
          {% load crispy_forms_tags %}
          {% csrf_token %}
          {{ havuz_arac_form|crispy }}
          <button class="btn btn-outline-success w-25 mx-auto" type="submit">Kaydet</button>
        </form>

    </div>
  </div>



  <div class="col-12 col-md-7 d-flex flex-column align-items-center">
    <h3 class="text-center text-success mb-3">Havuz Araç Kayıtları</h3>
    <div class="w-100 p-3">
      <ul class="list-group list-group-numbered overflow-auto" style="max-height:50vh;">
        {% if havuz_araclari %}
          {% for havuz_araci in havuz_araclari %}
        <li class="list-group-item mb-1">

            <table class="table table-bordered table-sm mb-0">
              <tbody>
                <tr>
                  <th>Çalışan</th>
                  <td>{{ havuz_araci.calisan }}</td>
                </tr>
                <tr>
                  <th>Plaka</th>
                  <td>{{ havuz_araci.plaka }}</td>
                </tr>
                <tr>
                  <th>Başlangıç KM</th>
                  <td>{{ havuz_araci.baslangic_km }}</td>
                </tr>
                <tr>
                  <th>Son KM</th>
                  <td>{{ havuz_araci.son_km }}</td>
                </tr>
                <tr>
                  <th>Net KM</th>
                  <td>{{ havuz_araci.net_km }}</td>
                </tr>
                <tr>
                  <th>Gideceği Yer</th>
                  <td>{{ havuz_araci.gidecegi_yer }}</td>
                </tr>
                <tr>
                  <th>Açıklama</th>
                  <td>{{ havuz_araci.aciklama }}</td>
                </tr>
                <tr>
                  <th>İçeride mi?</th>
                  <td>{{ havuz_araci.is_inside }}</td>
                </tr>
                <tr>
                  <th>Giriş Tarihi</th>
                  <td>{{ havuz_araci.giris_tarihi_saati|date:"d.m.Y H:i" }}</td>
                </tr>
                <tr>
                  <th>Çıkış Tarihi</th>
                  <td>{{ havuz_araci.cikis_tarihi_saati|date:"d.m.Y H:i" }}</td>
                </tr>
              </tbody>
            </table>
          
        </li>
          {% endfor %}
        {% else %}
        <li class="list-group-item">Kayıt yok!</li>
        {% endif %}
      </ul>
    </div>
  </div>


</div>

securityControl/templates/components/home-layout.html
  <h3 class="text-center text-success text-opacity-50">{{ page_title }}</h3>
<div class="container d-flex justify-content-center align-items-center mt-3">
  <div class="row row-cols-1 row-cols-md-2 g-4 justify-content-center text-center" style="max-width: 700px;">
    {% if sc_pages %}
    {% for page in sc_pages %}
      <a href="{% url 'sc:sec-home-views' page_slug=page.slug %}" class="nav-link">
        <div class="col d-flex justify-content-center">

          <div class="card zoom-card" style="{% if sc_pages.leng > 3 %}width: 80%; max-width: 250px;{% else %}width: 80%; max-width: 777px;{% endif %}">

            <img src="{{ page.img.url }}" style="width:100%;height:150px;" class="card-img-top" alt="...">
            <h5 class="card-title mt-2">{{ page }}</h5>
          </div>
        </div>
      </a>
    {% endfor %}
    {% else %}
    <div class="col d-flex justify-content-center">

      <div class="card zoom-card" style="{% if sc_pages.leng > 3 %}width: 80%; max-width: 250px;{% else %}width: 80%; max-width: 777px;{% endif %}">

        <img src="https://picsum.photos/id/{{ page.pk }}/600/300" class="card-img-top" alt="...">
        <h5 class="card-title mt-2">Sayfa Bulunamadı!</h5>
      </div>
    </div>
    {% endif %}
  </div>
</div>
</div>

{% block style %}
<style>
.zoom-card {
  transition: transform 0.3s ease-in;
}
.zoom-card:hover {
  transform: scale(1.05);
}
</style>
{% endblock style %}

securityControl/templates/components/sc_navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">

    <a class="navbar-brand m-0 me-3 p-0 btn btn-outline-secondary opacity-50" href="{% url 'fotoblog:home_views' %}">

      <img src="{{ page_logo.img.url }}" class="m-0 me-1 p-0" style="width:77px;height:33px;" alt=""></a>
    
    <a class="navbar-brand text-success" href="/securitycontrol/">Güvenlik Kontrol</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse gap-1" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="/securitycontrol/">Ana Sayfa</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Menü
          </a>
          <ul class="dropdown-menu">
            {% if sc_pages %}
              {% for g_page in sc_pages %}
            <li><a class="dropdown-item" href="{% url 'sc:sec-home-views' page_slug=g_page.slug %}">{{ g_page.title }}</a></li>
              {% endfor %}
            {% endif %}
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" aria-disabled="true">Disabled</a>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search"/>
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
        <a href="/admin/" target="_blank" class="btn btn-outline-danger" type="submit">Admin Panel</a>
    </div>
  </div>
</nav>

securityControl/templates/components/taseron-layout.html
<div class="row d-flex justify-content-around">
  <div class="col-12 col-md-4 d-flex flex-column align-items-center">
  <h3 class="text-center text-success mb-3">Taşeron Kayıt</h3>
    <div class="w-100">

      <button class="btn btn-outline-info mb-1" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasScrolling" aria-controls="offcanvasScrolling">+Ziyaretçi Ekle</button>

      <div class="offcanvas offcanvas-start" data-bs-scroll="true" data-bs-backdrop="false" tabindex="-1" id="offcanvasScrolling" aria-labelledby="offcanvasScrollingLabel">
        <div class="offcanvas-header">
          <h5 class="offcanvas-title" id="offcanvasScrollingLabel">Ziyaretçi Kayıt Formu</h5>
          <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
        </div>
        <div class="offcanvas-body">
          {% include 'components/ziyaretci-layout.html' with location=location %}
        </div>
      </div>

        <form action="" method="post" class="row flex-column mb-3 g-3">
          {% load crispy_forms_tags %}
          {% csrf_token %}
          
          {{ taseron_form|crispy }}
          
          <button class="btn btn-outline-success w-25 mx-auto" type="submit">Kaydet</button>
        </form>

    </div>
  </div>



  <div class="col-12 col-md-7 d-flex flex-column align-items-center">
    <h3 class="text-center text-success mb-3">Taşeronlar</h3>
    <div class="w-100 p-3">
      <ul class="list-group list-group-numbered overflow-auto" style="max-height:50vh;">
        {% if taseronlar %}
          {% for taseron in taseronlar %}
        <li class="list-group-item mb-1">
          <div>Firma : {{ taseron.firma_adi }}</div>
          <div>Ad / Soyad : {{ taseron.ziyaretci.first_name }} {{ taseron.ziyaretci.last_name }}</div>
          <div>Davet Eden : {{ taseron.davet_eden }}</div>
          <div>Yapılacak İş : {{ taseron.yapilacak_is }}</div>
          <div>Çalışma Alanı : {{ taseron.calisma_alani }}</div>
          <div>Giriş Tarihi : {{ taseron.created_at }}</div>
        </li>
          {% endfor %}
        {% else %}
        <li class="list-group-item">Kayıt yok!</li>
        {% endif %}
      </ul>
    </div>
  </div>


</div>

securityControl/templates/components/yuk-arac-layout.html
<div class="row d-flex justify-content-around">
  <div class="col-12 col-md-4 d-flex flex-column align-items-center">
  <h3 class="text-center text-success mb-3">Yük Araçları Kayıt</h3>
    <div class="w-100">


      <button class="btn btn-outline-info mb-1" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasScrolling" aria-controls="offcanvasScrolling">+Şoför Ekle</button>

      <div class="offcanvas offcanvas-start" data-bs-scroll="true" data-bs-backdrop="false" tabindex="-1" id="offcanvasScrolling" aria-labelledby="offcanvasScrollingLabel">
        <div class="offcanvas-header">
          <h5 class="offcanvas-title" id="offcanvasScrollingLabel">Şoför Kayıt Formu</h5>
          <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
        </div>
        <div class="offcanvas-body">
          {% include 'components/ziyaretci-layout.html' with location=location %}
        </div>
      </div>
      

        <form action="" method="post" class="row flex-column mb-3 g-3">
          {% load crispy_forms_tags %}
          {% csrf_token %}
          {{ yuk_arac_form|crispy }}
          <button class="btn btn-outline-success w-25 mx-auto" type="submit">Kaydet</button>
        </form>

    </div>
  </div>



  <div class="col-12 col-md-7 d-flex flex-column align-items-center">
    <h3 class="text-center text-success mb-3">Yük Araçları</h3>
    <div class="w-100 p-3">
      <ul class="list-group list-group-numbered overflow-auto" style="max-height:80vh;">
        {% if yuk_araclari %}
          {% for yuk_araci in yuk_araclari %}
        <li class="list-group-item mb-1"><div class="table-responsive">
            <table class="table table-bordered table-sm mb-0">
              <tbody>
                <tr>
                  <th>Şoför</th>
                  <td>{{ yuk_araci.sofor.first_name }} {{ yuk_araci.sofor.last_name }}</td>
                </tr>
                <tr>
                  <th>Çekici Plaka</th>
                  <td>{{ yuk_araci.cekici_plaka }}</td>
                </tr>
                <tr>
                  <th>Dorse Plaka</th>
                  <td>{{ yuk_araci.dorse_plaka }}</td>
                </tr>
                <tr>
                  <th>Firma Adı</th>
                  <td>{{ yuk_araci.firma_adi }}</td>
                </tr>
                <tr>
                  <th>Araç Türü</th>
                  <td>{{ yuk_araci.arac_turu }}</td>
                </tr>
                <tr>
                  <th>Sevkiyat Bölümü</th>
                  <td>{{ yuk_araci.sevkiyat_bolumu }}</td>
                </tr>
                <tr>
                  <th>Gideceği Yer</th>
                  <td>{{ yuk_araci.gidecegi_yer }}</td>
                </tr>
                <tr>
                  <th>İçeride mi?</th>
                  <td>{{ yuk_araci.is_inside }}</td>
                </tr>
                <tr>
                  <th>Oluşturulma</th>
                  <td>{{ yuk_araci.created_at }}</td>
                </tr>
                <tr>
                  <th>Güncellenme</th>
                  <td>{{ yuk_araci.updated_at }}</td>
                </tr>
              </tbody>
            </table>
          </div></li>
          {% endfor %}
        {% else %}
        <li class="list-group-item">Kayıt yok!</li>
        {% endif %}
      </ul>
    </div>
  </div>


</div>

securityControl/templates/components/ziyaretci-layout.html
<div class="row d-flex justify-content-around">
  <div class="col-12 col-md-4 d-flex flex-column align-items-center">
  <h3 class="text-center text-success mb-3">Ziyaretçi Kayıt</h3>
    <div class="w-100">
      
        <form action="{% url 'sc:sec-home-views' page_slug='ziyaretci' location=location %}" method="post" class="row flex-column mb-3 g-3">
          {% load crispy_forms_tags %}
          {% csrf_token %}
          {{ ziyaretci_form|crispy }}
          <button class="btn btn-outline-success w-25 mx-auto" type="submit">Kaydet</button>
        </form>
      
    </div>
  </div>


  
  <div class="col-12 col-md-7 d-flex flex-column align-items-center">
    <h3 class="text-center text-success mb-3">Ziyaretçiler</h3>
    <div class="w-100 p-3">
      <ul class="list-group list-group-numbered overflow-auto" style="max-height:50vh;">
        {% if ziyaretciler %}
          {% for ziyaretci in ziyaretciler %}
        <li class="list-group-item mb-1">{{ ziyaretci.first_name }} {{ ziyaretci.last_name }}</li>
          {% endfor %}
        {% else %}
        <li class="list-group-item">Kayıt yok!</li>
        {% endif %}
      </ul>
    </div>
  </div>

  
</div>