config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("securitycontrol/", include("securityControl.urls", namespace="sc")),
    path("", include("fotoblog.urls", namespace="fotoblog")),
]

fotoblog/urls.py
from django.urls import path
from fotoblog.views import page_views, post_detail_views


app_name = "fotoblog"

urlpatterns = [
    path("", page_views, name="home_views"),
    path("<slug:page_slug>/", page_views, name="page_views"),
    path("<slug:page_slug>/<slug:post_slug>", page_views, name="page_views"),
    path("<slug:page_slug>/<slug:post_slug>/<int:post_id>",
         post_detail_views,
         name="post_details"),
]

fotoblog/models.py
from django.db import models
from autoslug import AutoSlugField
from django.contrib.auth.models import User
from django.urls import reverse


class BaseModel(models.Model):
    title = models.CharField(max_length=100, blank=False, null=False)
    slug = AutoSlugField(populate_from="title")
    content = models.TextField(blank=True, null=True)
    img = models.FileField(upload_to="page_img/")
    is_active = models.BooleanField(default=True)

    class Meta:
        abstract = True


class Page(BaseModel):

    def __str__(self):
        return self.title


class Post(BaseModel):
    user = models.ForeignKey(User,
                             on_delete=models.CASCADE,
                             blank=False,
                             null=False)

    def __str__(self):
        return self.title


class FavPost(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    is_selected = models.BooleanField(default=False)


class PageLogo(models.Model):
    img = models.FileField(upload_to="page_logo/")

fotoblog/forms/forms.py
from django import forms
from fotoblog.models import Page,Post


class PageForm (forms.ModelForm):
    class Meta:
        model = Page
        fields = "__all__"
        


class PostForm (forms.ModelForm):
    class Meta:
        model = Post
        fields = "__all__"

fotoblog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from fotoblog.models import Page, Post, FavPost
from fotoblog.forms.forms import PageForm, PostForm
from django.contrib import messages
from django.contrib.auth import authenticate
from django.contrib.auth import login as auth_login, logout
from django.contrib.auth.models import User
from django.utils.text import slugify
from django.core.paginator import Paginator


def page_views(request,
               page_slug=None,
               post_slug=None,
               post_detail_slug=None,
               post_id=None):
    if post_id:
        return post_detail_views(request, post_id)
    if post_slug:
        return post_share(request, post_slug)
    if page_slug == "login":
        return login_views(request)
    if page_slug == "logout":
        return logout_views(request)
    if page_slug == "register":
        return register(request)
    if page_slug == "post-share":
        return post_share(request)
    if page_slug == "fav-update":
        return fav_update(request)
    if page_slug == "favorites":
        return favorites_views(request, page_slug)
    if page_slug == "page-details":
        return post_detail_views(request, page_slug, post_slug)
    if page_slug and not page_slug == "home":
        page = get_object_or_404(Page, slug=page_slug, is_active=True)
        if page_slug == "add-page":
            if request.user.is_authenticated and request.user.is_superuser:
                return add_page(request, page_slug)
            else:
                return redirect("fotoblog:home_views")
    elif page_slug == None or page_slug == "home":
        p_posts = Post.objects.filter(is_active=True).order_by("-id")
        set_posts = Paginator(p_posts, 3)
        page_number = request.GET.get("page")
        posts = set_posts.get_page(page_number)
        title = "Home"
        page = get_object_or_404(Page, slug="home", is_active=True)
        context = dict(
            posts=posts,
            page=page,
        )
        return render(request, "fb_pages/page-views.html", context)
    context = dict(page=page, )
    return render(request, "fb_pages/page-views.html", context)


def add_page(request, page_slug):
    if request.method == "POST":
        page_form = PageForm(request.POST, request.FILES)
        if page_form.is_valid():
            form_title = request.POST.get("title")
            is_page = Page.objects.filter(title__icontains=form_title).exists()
            if not is_page:
                page_form.save()
                messages.success(request,
                                 "The page has been successfully added!")
            else:
                messages.warning(request, "Already exists!")
            return redirect("fotoblog:home_views")
    else:
        page_form = PageForm()
    context = dict(page_form=page_form,
                   page=get_object_or_404(Page, slug=page_slug))
    return render(request, "fb_pages/page-views.html", context)


def login_views(request):
    title = "Login"
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")
        login_user = authenticate(username=username, password=password)
        if login_user is not None:
            auth_login(request, login_user)
            messages.info(request, "Logged in successfuly!")
            return redirect("fotoblog:home_views")
        else:
            messages.warning(request, "Invalid username or password!")
    context = dict(page_title=title, )
    return render(request, "fb_pages/login-page.html", context)


def logout_views(request):
    logout(request)
    messages.success(request, "Logged out successfuly!")
    return redirect("fotoblog:home_views")


def register(request):
    title = "Register"
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")
        confirm_password = request.POST.get("confirm_password")
        if password == confirm_password:
            register_user = authenticate(username=username, password=password)
            if register_user is not None:
                auth_login(request, register_user)
                messages.warning(request, "User is already exists!")
                return redirect("fotoblog:home_views")
            else:
                User.objects.create_user(username=username, password=password)
                messages.success(request,
                                 "The user has been successfully registered!")
                return redirect("fotoblog:home_views")

    context = dict(page_title=title, )
    return render(request, "fb_pages/register-page.html", context)


def post_share(request, post_slug=None):
    post = None
    if post_slug:
        post = get_object_or_404(Post, slug=post_slug, is_active=True)
    if request.method == "POST":
        if post:
            post_form = PostForm(request.POST, request.FILES, instance=post)
        else:
            post_form = PostForm(request.POST, request.FILES)
        if post_form.is_valid():
            post_obj = post_form.save(commit=False)
            title = post_form.cleaned_data.get("title")
            slug = slugify(title)

            if not post:
                if Post.objects.filter(slug=slug).exists():
                    messages.warning(request, "Post already exists!")
                    return render(request, "fb_pages/post-share.html",
                                  {"post_form": post_form})
            else:
                if Post.objects.filter(slug=slug).exclude(id=post.id).exists():
                    messages.warning(
                        request,
                        "Another post with this title already exists!")
                    return render(request, "fb_pages/post-share.html",
                                  {"post_form": post_form})

            post_obj.slug = slug
            post_obj.save()
            if post:
                messages.success(request, "Post updated successfully!")
            else:
                messages.success(request, "Post saved successfully!")
            return redirect("fotoblog:home_views")
    else:
        post_form = PostForm(instance=post)

    return render(request, "fb_pages/post-share.html", {"post_form": post_form})


def fav_update(request):
    if request.method == "POST":
        fav_post = get_object_or_404(Post, slug=request.POST.get("buttonSlug"))
        favset, created = FavPost.objects.get_or_create(user=request.user,
                                                        post=fav_post)
        if not created:
            favset.is_selected = not favset.is_selected
            favset.save()
        else:
            favset.is_selected = True
            favset.save()
            messages.success(request, "Post saved to Favorites!")
        return redirect("fotoblog:home_views")


def favorites_views(request, page_slug):
    title = "Favorites"
    user = request.user
    page = get_object_or_404(Page, slug=page_slug, is_active=True)
    fav_posts = FavPost.objects.filter(is_selected=True, user=user)
    context = dict(page_title=title, fav_posts=fav_posts, page=page)
    return render(request, "fb_pages/page-views.html", context)


def post_detail_views(request, page_slug, post_slug, post_id):
    title = "Post Details"
    post = get_object_or_404(Post, id=post_id, slug=post_slug, is_active=True)
    page = get_object_or_404(Page, slug=page_slug)
    context = dict(
        page_title=title,
        post=post,
        page=page,
    )
    return render(request, "fb_pages/page-views.html", context)

fotoblog/templates/components/details-card.html
<div class="card text-center p-1 border border-0 mx-auto" style="max-width:1000px;">
      <small class="text-light bg-opacity opacity-25 border-0 rounded p-1">user : {{ post.user }}</small>
  <hr class="text-light">
  <img src="{{ post.img.url }}" class="card-img-top border border-0 rounded" alt="...">
  <div class="card-body">
    <h5 class="card-title">{{ post.title }}</h5>
    <p class="card-text">{{ post.content }}</p>
    <a href="{% url 'fotoblog:page_views' page_slug=page.slug %}" class="btn btn-primary">Home</a>
  </div>

  

fotoblog/templates/components/footer.html
<div class="card text-center my-auto">
  <div class="card-header">
    <ul class="nav nav-tabs card-header-tabs">
      <li class="nav-item">
        <a class="nav-link active" aria-current="true" href="#">Active</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" aria-disabled="true">Disabled</a>
      </li>
    </ul>
  </div>
  <div class="card-body">
    <h5 class="card-title">Special title treatment</h5>
    <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
    <a href="#" class="btn btn-primary">Go somewhere</a>
  </div>
</div>

fotoblog/templates/components/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary" data-bs-theme="dark">
  <div class="container-fluid">
    <a class="navbar-brand m-0 p-0" href="{% url 'fotoblog:home_views' %}">

      <img src="{{ page_logo.img.url }}" class="m-0 p-0" style="width:77px;height:33px;" alt=""> {{ request.user|truncatechars:10 }} laboratory
      
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav mx-auto">
        {% if g_fb_pages %}
        {% for g_page in g_fb_pages %}
        <a class="nav-link {% if forloop.first %}active{% endif %}" aria-current="page" href="{% url 'fotoblog:page_views' page_slug=g_page.slug %}">{{ g_page.title }}</a>
        {% endfor %}
        {% endif %}
      </div>
      {% if request.user.is_authenticated %}
      <a href="/logout/" class="btn btn-secondary text-decoration-none ">Logout | {{ request.user.username }}</a>
      <a href="/admin/" target="_blank" class="btn btn-secondary text-decoration-none ms-1 ">Admin Panel</a>
      {% else %}
      <a href="/login/" class="btn btn-secondary text-decoration-none ">Login</a>
      <a href="/register/" class="btn btn-secondary text-decoration-none ms-1 ">Register</a>
      {% endif %}
    </div>
  </div>
</nav>

fotoblog/templates/components/pagination.html
<hr class="text-light">
<nav aria-label="Page navigation example my-auto">
  <ul class="pagination justify-content-center">
    <li class="page-item">
      {% if posts.has_previous %}
    <a class="page-link" href="?page={{ posts.previous_page_number }}">Previous</a>
  {% else %}
    <a class="page-link {% if not posts.has_previous %}disabled{% else %}enable{% endif %}" href="#">Previous</a>
  {% endif %}
    </li>
        {% for post_page in posts.paginator.page_range %}
    <li class="page-item"><a class="page-link" href="?page={{ post_page }}">{{ post_page }}</a></li>
        {% endfor %}
        <li class="page-item">
    {% if posts.has_next %}
      <a class="page-link" href="?page={{ posts.next_page_number }}">Next</a>
      {% else %}
      <a class="page-link disabled" href="#">Next</a>
      {% endif %}
    </li>
  </ul>
</nav>

fotoblog/templates/components/post-card.html
{% if posts %}
{% for post in posts %}
<hr class="text-light">
            <div class="d-flex flex-fill card mb-3 border-0 text-center border border-success border-opacity-25">
              <div class="text-start"><small class="btn btn-primary m-1 opacity-50">{{ post.user }}</small></div>
              <div class="card-body text-light p-0 col-12 col-lg-8 mx-auto">
                <div>
                    <h5 class="card-title">{{ post.title }}</h5>
                    <p class="card-text my-1">{{ post.content|truncatewords:30 }}</p>
                </div>
                <img src="{{ post.img.url }}" class="img-fluid rounded" alt="">
            </div>
            <div class="w-50 mx-auto" style="min-width:333px;">
              <a href="{% url 'fotoblog:post_details' post_id=post.id post_slug=post.slug page_slug=page.slug %}" class="btn btn-outline-info btn-sm mx-auto my-1">Read more</a>
            {% if request.user.is_authenticated and request.user == post.user %}
            <a href="{% url 'fotoblog:page_views' page_slug=page.slug post_slug=post.slug %}" class="btn btn-outline-info btn-sm mx-auto my-1">Edit</a>
            {% endif %}
            {% if request.user.is_authenticated %}
            <button class="btn btn-sm btn-danger" btn-slug="{{ post.slug }}">❤️</button>
            {% endif %}
            </div>
        </div>
          {% endfor %}
{% elif fav_posts %}
  
{% for fav_post in fav_posts %}
            <div class="card mb-3 border-success text-center w-100" style="max-width:333px;">
              <div class="text-start"><small class="btn btn-primary m-1">{{ fav_post.post.user }}</small></div>
              <div class="card-body text-light">
                <div>
                    <h5 class="card-title">{{ fav_post.post.title }}</h5>
                    <p class="card-text my-1">{{ fav_post.post.content|truncatewords:10 }}</p>
                </div>
                <img src="{{ fav_post.post.img.url }}" class="img-thumbnail w-100 mx-1 my-auto"  alt="">
            </div>
            <div class="w-50 mx-auto">
              <a href="{{ fav_post.post.get_absolute_url }}" class="btn btn-outline-info btn-sm mx-auto my-1">Read more</a>
            {% if request.user.is_authenticated and request.user == fav_post.post.user %}
            <a href="{% url 'fotoblog:page_views' page_slug=page.slug post_slug=fav_post.post.slug %}" class="btn btn-outline-info btn-sm mx-auto my-1">Edit</a>
            {% endif %}
            {% if request.user.is_authenticated %}
            <button class="btn btn-sm btn-danger" btn-slug="{{ fav_post.post.slug }}">❤️</button>
            {% endif %}
            </div>
        </div>
          {% endfor %}


{% endif %}